version: '2'
services:
  ###
  # Add your pipeline here
  ###

  ###
  # mu.semte.ch stack
  ###
  integratorui:
    image: bde2020/integrator-ui:latest
    volumes:
      - ./config/integrator:/app/config
    environment:
      VIRTUAL_HOST: example.big-data-europe.eu
  monitor:
    image: bde2020/pipeline-monitor-frontend:0.2.2
    links:
      - identifier:backend
    environment:
      VIRTUAL_HOST: monitor.example.big-data-europe.eu
  identifier:
    image: semtech/mu-identifier:1.0.0
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    volumes:
      - ./config:/config
  database:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  pipeline:
    image: bde2020/mu-pipeline-service:0.1.0
  initdaemon:
    image: bde2020/mu-init-daemon-service:0.1.0
